version: '3'
services:

  homeassistant:
    container_name: ${HOMEASSISTANT_NAME}
    image: "ghcr.io/home-assistant/raspberrypi3-homeassistant:stable"
    volumes:
      - ./husvatetti/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    ports:
      - "8123:8123"

  plex:
    container_name: ${PLEX_NAME}
    image: "ghcr.io/linuxserver/plex"
    volumes:
      - ./config-plex:/config
    restart: unless-stopped
