version: '3'
services:

  homeassistant:
    container_name: ${HOMEASSISTANT_NAME}
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config:/config
    restart: unless-stopped
    privileged: true
    ports:
      - "8123:8123"
